name: Validate Documentation

on:
  push:
    paths:
      - /documentation/**
  pull_request:
    paths:
      - /documentation/**

jobs:
  main:
    name: Compile Source

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Cache Node Module Dependencies
        uses: actions/cache@v2
        with:
          path: "/documentation/node_modules"
          key: nodemodules-${{ runner.os }}-${{ hashFiles('/documentation/package-lock.json') }}

      - name: Install Dependencies
        working-directory: /documentation
        run: npm install

      - name: Build Source
        working-directory: /documentation
        run: npm run build
